### ISSUE TITLE
依赖环境问题

### ISSUE THREAD

**Issue by feiyihx** [2DIPW/GPT-SoVITS-RefAudio-Tester#2]
[RVC-Boss/GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS)是虚拟环境，基于runtime目录下的，所以我直接用：
runtime\python .\webui.py启动的本项目。
可是直接报错：
```
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "C:\Users\xuhug\Downloads\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "C:\Users\xuhug\Downloads\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\xuhug\Downloads\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\xuhug\Downloads\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xuhug\Downloads\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "C:\Users\xuhug\Downloads\GPT-SoVITS-beta\GPT-SoVITS-beta\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
```
请问有什么解决方案吗？因为是给我爸装的，直接在本地python安装依赖的话报building wheel unsuccessful错误。我知道这个错误该怎么解决，但是因为我爸做城规设计的，他们有个软件要依赖于本地python2.7以及一系列的特定版本的依赖，所以我不太想动他的本地环境。

两个项目是共用依赖的话，理论上应该是可以直接用[RVC-Boss/GPT-SoVITS](https://github.com/RVC-Boss/GPT-SoVITS)的虚拟环境运行本项目的呀？
谢谢！

**Comment by 2DIPW** [comment]
看您的报错`ImportError: FFmpeg libraries are not found. Please install FFmpeg.`应该是在torchaudio在import过程中找不到ffmpeg有关，请按原项目教程[这里](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/docs/cn/README.md#windows-%E4%BD%BF%E7%94%A8%E8%80%85)也在本项目GPT-SoVITS目录下放置ffmpeg.exe试试

**Comment by feiyihx** [comment]
> 看您的报错`ImportError: FFmpeg libraries are not found. Please install FFmpeg.`应该是在torchaudio在import过程中找不到ffmpeg有关，请按原项目教程[这里](https://github.com/RVC-Boss/GPT-SoVITS/blob/main/docs/cn/README.md#windows-%E4%BD%BF%E7%94%A8%E8%80%85)也在本项目GPT-SoVITS目录下放置ffmpeg.exe试试

因为电脑上要做视频处理的原因，ffmpeg是加在了path里面的。不过好像和这个没关系，在我自己的笔记本上用原项目的requirements.txt做了新的venv就没问题了。所以确实是完全一样的依赖，就是不知道为啥不能直接用原项目的虚拟环境。

本来想着完全一样的依赖环境可以直接用就好了。然后拉requirements.txt的时候先报cmaker和nmaker错误，又有python版本要求。也就是要装vs的c+环境，还要换python版本。我自己的台式机也就还好，可是回老家这边老爸的电脑因为软件需求就不好搞，我的笔记本性能又不够，就有点头疼。

Anyway，我还是用上了您的项目。另外，非常感谢您做了这个项目，真的省了好多事儿。笔芯~

**Comment by 2DIPW** [comment]
因为我是直接clone下来自己部署的，没有使用过原作者的整合包，所以不太清楚具体的原因。
不过您也确实提醒了我ffmpeg的问题，我也是将ffmpeg加入path的，所以开发的时候一直没有在意过这个问题，刚刚从path中去掉了ffmpeg后运行确实出错了，我会直接在repo中添加一份ffmpeg。

很高兴看到您的问题已解决，我将关闭此issue，如还有问题请另开issue。
